# Generated by Django 4.1.7 on 2023-06-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parking_area_no', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('parking_charge', models.FloatField(max_length=100)),
                ('vehicle_limit', models.IntegerField()),
                ('status', models.CharField(default='activated', max_length=10)),
                ('doc', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=200)),
                ('parking_area_no', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('parking_charge', models.FloatField()),
                ('arrival_time', models.DateTimeField(default=0)),
                ('status', models.CharField(default='parked', max_length=10)),
            ],
        ),
    ]
