# Generated by Django 4.1.7 on 2023-06-05 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
