# Generated by Django 4.1.7 on 2023-06-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_alter_vehicle_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
